app/userManagement/views.py
import os
import secrets
import time
from flask import Blueprint, render_template, url_for, request, flash, redirect, Markup
from flask_login.utils import login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from app.send_mail_sms import send_mail
from app.config import NYUPAL_SUPPORT_EMAIL
from werkzeug.utils import secure_filename
from app import db, mail, create_app
from app.models import User, Plans
from app.subscription_manager import subscription_manager
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Create Blueprint
auth_login_view = Blueprint('auth_login_view',
                            __name__,
                            static_folder='static',
                            template_folder='templates')


@auth_login_view.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_view.index', page_num=1))

    if request.method == 'POST':
        login_form = request.form
        login_email = login_form['loginEmail']
        login_pwd = login_form['loginPassword']
        login_remember = True if request.form.get("loginRemember") else False

        # * INPUT VALIDATION
        error = ""
        if login_email == "" or login_pwd == "":
            error = "Please fill in all the fields."
            flash(
                f"{error}")
            return redirect(url_for('auth_login_view.login'))

        user = User.query.filter_by(user_email=login_email).first()

        # Check if user (email) exists
        if user:
            if check_password_hash(user.user_pword, login_pwd):
                # flash("Login Successful.")
                login_user(user, remember=login_remember)
                #* If a user is a property owner, check subscription status.
                if user.businessAccount:
                    sub_plan = user.businessPlan
                    if not subscription_manager.validate:
                        flash(Markup(f"Your Subscription has Expired. Please <b><a href='{url_for('finance_view.checkout',plan=sub_plan)}'>update subscription.</a></b>"))
                    
                return redirect(url_for('main_view.index', page_num=1))
            else:
                error = 'Login Failed. Please try again.'
        else:
            error = 'Login Failed. Do you have an account?'

        if error:
            flash(f"{error}")
            return redirect(url_for('auth_login_view.login'))

    return render_template("userManagement/login.html")


@auth_login_view.route('/register/', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main_view.index', page_num=1))

    if request.method == 'POST':
        register_form = request.form
        register_fname = register_form['registerFirst']
        register_lname = register_form['registerLast']
        register_email = register_form['registerEmail']
        register_pwd = register_form['registerPassword']
        register_confirmPwd = register_form['registerConfirmPassword']
        register_updates = 1  # if request.form.get("registerUpdates") else 0

        # * INPUT VALIDATION
        error = ""
        if register_fname == "" or register_lname == "" or register_email == "" or register_pwd == "":
            error = "Please fill in all the fields."
            flash(
                f"{error}")
            return redirect(url_for('auth_login_view.register'))

        # * USER VALIDATION

        # Ensure email is unique
        emailsInDB = User.query.filter_by(user_email=register_email).first()
        if emailsInDB:
            error = "This Account Already Exists. Log in instead."

        # Ensure Passwords Match
        if register_pwd != register_confirmPwd:
            error = "The passwords do not match. Please Try Again."

        # * Edgecase-Failed: Redirect to register page for user to try again
        if error:
            flash(
                f"{error}")
            return redirect(url_for('auth_login_view.register'))

        # Newsletter Subscriptions?
        # unnecessary logic due to the one liner used above (register_updates)
        if register_updates:
            pass
            # register_updates = 1

        new_user = User(
            first_name=register_fname,
            last_name=register_lname,
            user_email=register_email,
            user_pword=generate_password_hash(register_pwd, method='sha256'),
            user_updates=register_updates
        )

        try:
            # Try adding user object to database.
            db.session.add(new_user)
            db.session.commit()

            flash(
                f"Your Account was Successfully Created. Proceed to Login")
            return redirect(url_for('auth_login_view.login'))
        except Exception as e:
            # Log this SERIOUS issue > Report to Developer
            error = e
            print(error)

    return render_template("userManagement/register.html")


@auth_login_view.route('/register_business/', methods=['GET', 'POST'])
def register_business():
    """Registers a business account. A business account can list and thus sell property
    on the platform
    """

    default_business_plan = int(Plans.query.filter_by(
        plan_name='Standard Business Account').first().id)
    print(f"default_business_plan: {default_business_plan}")
    if current_user.is_authenticated:
        return redirect(url_for('main_view.index', page_num=1))

    if request.method == 'POST':
        register_form = request.form
        register_fname = register_form['registerBusinessFirst']
        register_lname = register_form['registerBusinessLast']
        register_email = register_form['registerBusinessEmail']
        register_pwd = register_form['registerBusinessPassword']
        register_confirmPwd = register_form['registerBusinessConfirmPassword']
        register_updates = 1 if request.form.get(
            "registerBusinessUpdates") else 0

        # This is the only difference between a regular user and a seller / property owner
        businessAccount = 1  # Admin-ish feature
        businessName = register_form['registerBusinessName']

        # * INPUT VALIDATION
        error = ""
        if register_fname == "" or register_lname == "" or register_email == "" or register_pwd == "":
            error = "Please fill in all the required fields."
            flash(
                f"{error}")
            return redirect(url_for('auth_login_view.register'))

        # * USER VALIDATION

        # Ensure email is unique
        emailsInDB = User.query.filter_by(user_email=register_email).first()
        if emailsInDB:
            error = "This Account Already Exists. Log in instead."

        # Ensure Passwords Match
        if register_pwd != register_confirmPwd:
            error = "The passwords do not match. Please Try Again."

        # * Edgecase-Failed: Redirect to register page for user to try again
        if error:
            flash(
                f"{error}")
            return redirect(url_for('auth_login_view.register'))

        # Newsletter Subscriptions?
        # unnecessary logic due to the one liner used above (register_updates)
        if register_updates:
            pass
            # register_updates = 1

        new_user = User(
            first_name=register_fname,
            last_name=register_lname,
            user_email=register_email,
            user_pword=generate_password_hash(register_pwd, method='sha256'),
            user_updates=register_updates,
            businessAccount=businessAccount,
            businessName=businessName,
            businessPlan=default_business_plan
        )

        try:
            # Try adding user object to database.
            db.session.add(new_user)
            db.session.commit()

            flash(
                f"Your Account was Successfully Created. Proceed to Login")
            return redirect(url_for('auth_login_view.login'))
        except Exception as e:
            # Log this SERIOUS issue > Report to Developer
            error = e
            print(error)

    return render_template("userManagement/register_business.html")


@auth_login_view.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main_view.index', page_num=1))


@auth_login_view.route('/profile/', methods=['GET', 'POST'])
@login_required
def profile():
    accountType = current_user.businessAccount
    plan = None
    # Check if user is on business account; then get the business plan (tier)
    if accountType == 1:
        businessPlanID = current_user.businessPlan
        plan = Plans.query.filter_by(id=businessPlanID).first()
        print(plan)

    # Nyupal Contact
    nyupalContact = {
        'businessName': "Nyupal",
        "businessEmail": "support@nyupal.com",
        "businessPhone": "+254712345678",
    }

    if request.method == 'POST':
        editProfileForm = request.form
        profileFirst = editProfileForm['profileFirst']
        profileLast = editProfileForm['profileLast']
        profileEmail = editProfileForm['profileEmail']
        profilePhone = editProfileForm['profilePhone']

        # Not all Accounts are Business Accounts thus this field is optional.
        profileBusinessName = editProfileForm.get('profileBusinessName')

        # * INPUT VALIDATION
        error = ""
        if profileFirst == "" or profileLast == "" or profileEmail == "" or profilePhone == "":
            error = "Please fill in all the Required Fields."
            flash(
                f"{error}")
            return redirect(url_for('auth_login_view.profile'))

        #! IMAGE PROCESSING, MORE OR LESS
        profile_image = ''
        profile_image_name = None

app/userManagement/templates/userManagement/base.html
<!-- Not used. -->

<!doctype html>
<html lang="en">
  <head>
  	<title>Login 09</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{{ url_for('static', filename='userManagement/css/style.css') }}">

	</head>
    {% block content %}
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login #09</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap py-5">
		      	<div class="img d-flex align-items-center justify-content-center" style="background-image: url(images/bg.jpg);"></div>
		      	<h3 class="text-center mb-0">Welcome</h3>
		      	<p class="text-center">Sign in by entering the information below</p>
						<form action="#" class="login-form">
		      		<div class="form-group">
		      			<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-user"></span></div>
		      			<input type="text" class="form-control" placeholder="Username" required>
		      		</div>
	            <div class="form-group">
	            	<div class="icon d-flex align-items-center justify-content-center"><span class="fa fa-lock"></span></div>
	              <input type="password" class="form-control" placeholder="Password" required>
	            </div>
	            <div class="form-group d-md-flex">
								<div class="w-100 text-md-right">
									<a href="#">Forgot Password</a>
								</div>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="btn form-control btn-primary rounded submit px-3">Get Started</button>
	            </div>
	          </form>
	          <div class="w-100 text-center mt-4 text">
	          	<p class="mb-0">Don't have an account?</p>
		          <a href="#">Sign Up</a>
	          </div>
	        </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{{ url_for('static', filename='userManagement/js/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='userManagement/js/popper.js') }}"></script>
  <script src="{{ url_for('static', filename='userManagement/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='userManagement/js/main.js') }}"></script>

	</body>
    {% endblock content %}
</html>

app/userManagement/templates/userManagement/base2.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- <title>Hello, world!</title> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

  <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900'>
<link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Montserrat:400,700'>
<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/len-style.css') }}">
  </head>
  <body>
    <!-- <h1>Hello, world!</h1> -->
	{% block content%}

	{% endblock content%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="{{ url_for('static', filename='len-index.js') }}"></script>
  </body>
</html>

app/userManagement/templates/userManagement/login.html
{% extends "userManagement/base2.html" %} {% block content %}

<!-- <center> -->
{# Flashed Messages #} 
{% with messages = get_flashed_messages() %} 
{% if messages %} {% for message in messages %}
  <div class="alert alert-info alert-dismissible fade show mt-1" role="alert">
    <strong>{{ message }}</strong>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    >
      <span aria-hidden="true"></span>
    </button>
  </div>
  {% endfor %} {% endif %} {% endwith %}
  
  <div class="container">
    <div class="container">
      <div class="info">
        <h1>Sign into your Account</h1>
        <span><a href="#">&copy; Nyupal - All Rights Reserved</a></span>
      </div>
    </div>
    <div class="form">
      <div class="thumbnail">
        <img src="{{ url_for('auth_login_view.static', filename='userManagement/users/nicon.png') }}"
        width="150" />
      </div>
      <form
        action="{{ url_for('auth_login_view.login') }}"
        method="POST"
        class="login-form"
      >
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <input
          type="text"
          placeholder="name@example.com"
          name="loginEmail"
          required
        />
        <input
          type="password"
          placeholder="Password"
          name="loginPassword"
          required
        />
        <button type="submit">Login</button>
        <p class="message">
          Forgot Password?
          <a href="{{ url_for('auth_login_view.reset_request') }}">Click Here.</a>
        </p>
        <p class="message">
          Don't have an Account?
          <a href="{{ url_for('auth_login_view.register') }}"><strong>Sign Up.</strong></a>
        </p>
      </form>
    </div>
  </div>

{% endblock content %}

app/userManagement/templates/userManagement/register.html
{% extends "userManagement/base2.html" %} {% block content %}



<!-- <center> -->
{# Flashed Messages #} 
{% with messages = get_flashed_messages() %} 
{% if messages %} 
{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show mt-1" role="alert">
  <strong>{{ message }}</strong>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  >
    <span aria-hidden="true"></span>
  </button>
</div>
{% endfor %} {% endif %} {% endwith %}

<div class="container">
  <div class="container">
    <div class="info">
      <h1>Sign Up</h1>
      <span><a href="#">&copy; Nyupal - All Rights Reserved</a></span>
    </div>
  </div>

  <div class="form">
    <div class="thumbnail">
      <img src="{{ url_for('auth_login_view.static', filename='userManagement/users/nicon.png') }}"
        width="150" />
    </div>
    <form
      action="{{ url_for('auth_login_view.register') }}"
      method="POST"
      class="login-form"
    >
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <!-- <div class="row"> -->
        <!-- <div class="col"> -->
        <input
          type="text"
          placeholder="First name"
          name="registerFirst"
          required
        />
      <!-- </div> -->
      <!-- <div class="col"> -->
        <input
          type="text"
          placeholder="Last name"
          name="registerLast"
          required
        />
        <!-- </div> -->
      <!-- </div> -->
      <input
        type="email"
        placeholder="name@example.com"
        name="registerEmail"
        required
      />
      <input
        type="password"
        placeholder="Password"
        name="registerPassword"
        required
      />
      <input
        type="password"
        placeholder="Confirm Password"
        name="registerConfirmPassword"
        required
      />

      <button type="submit">Create Account</button>
      <p class="message">
        Already have an Account?
        <a href="{{ url_for('auth_login_view.login') }}">Click Here.</a>
      </p>
      <hr>
      <p class="message">
        Want to List Property?
        <a href="{{ url_for('auth_login_view.register_business') }}">Click Here.</a>
      </p>
    </form>
  </div>
</div>


{% endblock content %}

app/userManagement/templates/userManagement/register_business.html
{% extends "userManagement/base2.html" %} {% block content %}


<!-- <center> -->
{# Flashed Messages #} 
{% with messages = get_flashed_messages() %} 
{% if messages %} 
{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show mt-1" role="alert">
  <strong>{{ message }}</strong>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  >
    <span aria-hidden="true"></span>
  </button>
</div>
{% endfor %} {% endif %} {% endwith %}

<div class="container">
  <div class="container">
    <div class="info">
      <h1>Business</h1>
      <span><a href="#">&copy; Nyupal - All Rights Reserved</a></span>
    </div>
  </div>

  <div class="form">
    <div class="thumbnail">
      <img src="{{ url_for('auth_login_view.static', filename='userManagement/users/nicon.png') }}"
        width="150" />
    </div>
    <form
      action="{{ url_for('auth_login_view.register_business') }}"
      method="POST"
      class="login-form"
    >
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <input
          type="text"
          placeholder="First name"
          name="registerBusinessFirst"
          required
        />
        <input
          type="text"
          placeholder="Last name"
          name="registerBusinessLast"
          required
        />
      <input
          type="text"
          placeholder="Business name (Optional)"
          name="registerBusinessName"
          required
        />
      <input
        type="email"
        placeholder="name@example.com"
        name="registerBusinessEmail"
        required
      />
      <input
        type="password"
        placeholder="Password"
        name="registerBusinessPassword"
        required
      />
      <input
        type="password"
        placeholder="Confirm Password"
        name="registerBusinessConfirmPassword"
        required
      />

      <button type="submit">Create Business Account</button>
      <p class="message">
        Already have an Account?
        <a href="{{ url_for('auth_login_view.login') }}">Click Here.</a>
      </p>
      <hr>
      <p class="message">
        Just Visiting?
        <a href="{{ url_for('auth_login_view.register') }}">Click Here.</a>
      </p>
    </form>
  </div>
</div>

{% endblock content %}

app/userManagement/templates/userManagement/reset_pword.html
{% extends "userManagement/base2.html" %} {% block content %}

<!-- <center> -->
{# Flashed Messages #}
{% with messages = get_flashed_messages() %} 
{% if messages %} 
{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show mt-1" role="alert">
  <strong>{{ message }}</strong>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  >
    <span aria-hidden="true"></span>
  </button>
</div>
{% endfor %} {% endif %} {% endwith %}

<div class="container">
  <div class="container">
    <div class="info">
      <h1>Reset your Password</h1>
      <span><a href="#">&copy; Nyupal - All Rights Reserved</a></span>
    </div>
  </div>
  <div class="form">
    <div class="thumbnail">
      <img src="{{ url_for('auth_login_view.static', filename='userManagement/users/nicon.png') }}"
        width="150" />
    </div>
    <form action="" method="POST" class="login-form">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

      <input
        type="password"
        placeholder="New Password"
        name="resetPassword"
        required
      />
      <input
        type="password"
        placeholder="Confirm New Password"
        name="resetConfirmPassword"
        required
      />
      <button type="submit">Confirm New Password</button>
    </form>
  </div>
</div>











{% endblock content %}

app/userManagement/templates/userManagement/reset_request.html
{% extends "userManagement/base2.html" %} {% block content %}

<!-- <center> -->
{# Flashed Messages #} 
{% with messages = get_flashed_messages() %} 
{% if messages %} 
{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show mt-1" role="alert">
  <strong>{{ message }}</strong>
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  >
    <span aria-hidden="true"></span>
  </button>
</div>
{% endfor %} {% endif %} {% endwith %}

  <div class="container">
    <div class="container">
      <div class="info">
        <h1>Reset Your Password</h1>
        <span><a href="#">&copy; Nyupal - All Rights Reserved</a></span>
      </div>
    </div>
    <div class="form">
      <div class="thumbnail">
        <img src="{{ url_for('auth_login_view.static', filename='userManagement/users/nicon.png') }}"
        width="150" />
      </div>
      <form
        action="{{ url_for('auth_login_view.reset_request',token=token) }}"
        method="POST"
        class="login-form"
      >
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <input
          type="text"
          placeholder="name@example.com"
          name="resetEmail"
          required
        />
        <button type="submit">Send Reset Link</button>
      </form>
    </div>
  </div>



{% endblock content %}