app/business/views.py
import os
import time
import secrets
import cloudinary
import cloudinary.api
import cloudinary.uploader
from app import db, mail, create_app, aws_client
from app.send_mail_sms import send_mail
# from app.config import VERIFICATION_PATH, AWS_S3_BUCKET, ALLOWED_IMAGE_EXTENSIONS
from werkzeug.utils import secure_filename
from app.subscription_manager import subscription_manager
from flask_login.utils import login_required, logout_user
from app.models import Plans, User, Property, PropertyDocuments
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from flask import Blueprint, render_template, url_for, request, flash, redirect, Markup

# Create Blueprint
business_admin_view = Blueprint('business_admin_view',
                                __name__,
                                static_folder='static',
                                template_folder='templates')


@business_admin_view.route('/', methods=['GET', 'POST'])
@login_required
def property_dashboard():
    # Check if user is admin!
    if current_user.businessAccount != 1:
        return redirect(url_for('main_view.index',page_num=1))

    # list of properties listed / owned by the user.
    propertys = current_user.property
    print(f'propertys {propertys}')

    # business plan
    userPlan = Plans.query.filter_by(id=current_user.businessPlan).first()

    #? Verification Status and Text => DB.Json Column?
    verification_dict = {
        0:('btn-warning','verification pending','We are currently working on getting your property verified.'),
        1:('btn-success','verified','Your property has been successfully verified!'),
        2:('btn-danger','verification failed','Your property does not meet requirements for verification. Contact us for more info.'),
        3:('btn-danger','verification flagged','Your property does not meet requirements for verification. Contact us for more info.'),
    }

    # Property_PropertyDocuments
    property_verification_status = {}
    verification_prompt = 4
    for p in propertys:
        print(f'p; {p}')
        # docs = PropertyDocuments.query.filter_by(property_id=p.id).first()
        docs = p.documents
        print(f'docs; {docs}')
        if docs:
            property_verification_status[p] = docs[0].verified
        else:
            #* verification_prompt is an arbitrary flag that'll be used to dynamically alter the UI
            property_verification_status[p] = verification_prompt

    # Get the images
    propertyImages = []
    for prop in propertys:
        propImages = prop.property_images.split('|')
        profilePic = propImages[0]
        propertyImages.append(profilePic)

    #! Check whether subscription has expired.
    sub_plan = current_user.businessPlan
    if not subscription_manager.validate:
        flash(Markup(f"Your Subscription has Expired. Please <b><a href='{url_for('finance_view.checkout',plan=sub_plan)}'>update subscription.</a></b>"))
    

    return render_template("business/dashboard.html",
                           propertys=propertys,
                           propertyImages=propertyImages,
                           userPlan=userPlan,
                           verification_dict=verification_dict,
                           property_verification_status=property_verification_status,
                           verification_prompt=verification_prompt)


@business_admin_view.route('/add/', methods=['GET', 'POST'])
@login_required
def add_property():
    # Check if user is admin!
    if current_user.businessAccount != 1:
        return redirect(url_for('main_view.index',page_num=1))

    propertyTypes = ["Residential", "Commercial", "Land"]
    # This will be used to display and Ad on the Add-Property Page
    bannerAd = url_for('static', filename='icons/banner.jpg')

    if request.method == 'POST':
        registerProperty_form = request.form
        newPropertyName = registerProperty_form['newPropertyName']
        newPropertyDescription = registerProperty_form['newPropertyDescription'].strip()
        newPropertyType = registerProperty_form['newPropertyType']
        newPriceRange = registerProperty_form['newPriceRange']
        newPropertyLocation = registerProperty_form['newPropertyLocation']
        newPropertyMisc = registerProperty_form['newPropertyMisc']
        newContactName = registerProperty_form['newContactName']
        newPhoneNumber = registerProperty_form['newPhoneNumber']
        newBusinessName = registerProperty_form['newBusinessName']

        # * INPUT VALIDATION
        error = ""
        if newPropertyName == "" or newPropertyDescription == "" or newPropertyType not in propertyTypes or newPriceRange == "" or newPropertyLocation == "" or newContactName == "" or newPhoneNumber == "":
            error = "Please fill in all the Required Fields."
            flash(
                f"{error}")
            return redirect(url_for('business_admin_view.add_property'))

        #! IMAGE PROCESSING, MORE OR LESS
        cloudinary.config(cloud_name=os.getenv('CLOUD_NAME'), api_key=os.getenv('API_KEY'),
                          api_secret=os.getenv('API_SECRET'))
        if request.files != None:
            # Main Image
            propertyProfilePic = request.files['addPropertyProfilePic']
            # Required Secondary Image
            propertySecondaryImage1 = request.files['addPropertySecondaryImage1']
            #! I am thinking of not imposing restrictions on required vs optional images here. (Add Property??)
            # ? Important Question: Also, what if a user wants to change one of the images and not all of them?
            # Optional Secondary Image
            propertySecondaryImage2 = request.files['addPropertySecondaryImage2']
            # Optional Secondary Image
            propertySecondaryImage3 = request.files['addPropertySecondaryImage3']
            # print(editPropertySecondaryImage1.filename)

            expectedImagesList = [propertyProfilePic, propertySecondaryImage1,
                                  propertySecondaryImage2, propertySecondaryImage3]

            propertyImagesCombined = ''
            for index, img in enumerate(expectedImagesList):
                property_images = ''
                #! SECURITY CHECK - Do not allow malicious uploads
                if img.filename:
                    # * 2. Ensure file extension is allowed. (Images only) -> As defined in config.py
                    # print(img.filename)
                    if allowed_image(img.filename):
                        # print(os.getcwd())
                        # * 3. Ensure the file itself isn't dangerous.
                        img_filename = secure_filename(img.filename)
                        # image = property/{property_type}/random_str_timestamp.extension
                        property_images = f'property/{newPropertyType.lower()}/{secrets.token_hex(2)}{secrets.token_hex(3)}_{str(time.time()).split(".")[0]}.{img_filename.split(".")[-1].lower()}'
                        # print(img_filename)
                        # print(property_images)
                        #! Restrict Filesize
                        # ? By default Flask throws a HTTP 413 error if MAX_CONTENT_LENGTH is exceeded.
                        # Save the image
                        img.save(os.path.join(
                            create_app().config["IMAGE_UPLOADS_PROPERTY"], property_images))
                        cloudinary_imgFilename = os.path.join(create_app().config["IMAGE_UPLOADS_PROPERTY"],property_images)
                        # print(cloudinary_imgFilename)
                        upload_result = cloudinary.uploader.upload(cloudinary_imgFilename)
                        print(f"upload_result: {upload_result['secure_url']}")
                        property_images = upload_result['secure_url']

                    else:
                        error_message = "Please upload an image with accepted extension (.png, .jpeg, .jpg)"
                        flash(f"{error_message}")
                        print(error_message)
                        return redirect(url_for('business_admin_view.add_property', property_id=property.id))

                 # Format the Property Image string ('|' separated)

                else:
                    break

                propertyImagesCombined += f'{property_images}|'

                # if index == len(expectedImagesList)-1:
                #     propertyImagesCombined += f'{property_images}'
                # else:
                #     propertyImagesCombined += f'{property_images}|'

        # * 'Filtration' Process
        # remove any empty fields
        propertyImagesCombinedList = [
            i for i in propertyImagesCombined.split('|') if i]
        propertyImagesCombinedString = ''
        for index, i in enumerate(propertyImagesCombinedList):
            if index != len(propertyImagesCombinedList)-1:
                propertyImagesCombinedString += f'{i}|'
            else:
                propertyImagesCombinedString += f'{i}'

        if not len(propertyImagesCombinedString) > 10:
            #! Refer to Important Question above for more details; why this isn't a sustainable implementation.
            # property.property_images = propertyImagesCombinedString
            # print(propertyImagesCombinedString)
            error = "Please Upload The Required Images."
            flash(
                f"{error}")
            return redirect(url_for('business_admin_view.add_property'))

        new_property = Property(
            property_name=newPropertyName,
            property_description=newPropertyDescription,
            property_price=newPriceRange,
            property_type=newPropertyType,
            property_location=newPropertyLocation,
            property_images=propertyImagesCombinedString,
            property_features=newPropertyMisc,
            property_owner=current_user.id,

app/views.py
from flask import (Blueprint,
                   request,
                   make_response,
                   jsonify,
                   render_template,
                   flash)
from flask_login import current_user
from app.models import Property, Rating, User
from app import db

# Create Blueprint
main_view = Blueprint('main_view', __name__)

@main_view.route('/')
@main_view.route('/<int:page_num>/')
def index(page_num=1):
    propertys = Property.query.paginate(
        per_page=12, page=page_num, error_out=True)

    propertyImages = []
    property_verified = {}
    for property in propertys.items:
        # print(f"propertyDocs: {property.documents}")
        # Getting the image dirs
        images = property.property_images.split('|')
        profilePic = images[0]  # get the primary image (property_profile_pic)
        propertyImages.append(profilePic)
        owner = User.query.filter_by(id=property.property_owner).first()
        if property.documents:
            #! is this check justified?
            if owner:
                property_verified[property.id] = 1 if property.documents[0].verified == 1 else 0

    # print(propertyImages)

    return render_template("index.html",
                           propertys=propertys,
                           propertyImages=propertyImages,
                           property_verified=property_verified)


@main_view.route('/rating-clicked', methods=['POST'])
def rating_clicked():
    """Receives the rating; when a user stars a property
    THIS FUNCTION IS CALLED ASYNCHRONOUSLY BY THE JS FETCH API FROM THE FRONTEND

    Returns:
        json: success
    """
    rating_object = request.get_json()
    property_id = rating_object.get('string_id').split('_')[-1]
    property_rating = rating_object.get('rating')

    print(property_id,
          property_rating)

    new_rating = Rating(
        user_id=int(current_user.id),
        property_id=int(property_id),
        rating=property_rating
    )

    try:
        db.session.add(new_rating)
        db.session.commit()
        print("Rating Success")
    except Exception as e:
        flash("Failed to Rate building")
        #! Log Error.
        print(f"Failed to Rate building: {e}")

    response = make_response(jsonify({"result": "success"}), 200)

    return response

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Popper -->
    <!--! Bootstrap bundle includes Popper -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"> -->

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

    <!-- My Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/my-style.css') }}">

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- Fontawesome Kit -->
    <script src="https://kit.fontawesome.com/5566bd828d.js" crossorigin="anonymous"></script>

    <title>NYUPAL</title>
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main_view.index',page_num=1) }}">
          <img
            src="{{ url_for('static', filename='icons/hnyupal.png') }}"
            alt=""
            height="50"
            class="d-inline-block align-text-top"
          />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            
          </ul> -->

          <form class="d-flex mx-auto">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-primary" type="submit">
              Search
            </button>
          </form>

          {% if current_user.is_authenticated %}

          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item dropstart">
              <a
                class="nav-link active dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                {{ current_user.first_name }} {{ current_user.last_name }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{{ url_for('auth_login_view.profile') }}">View Profile</a></li>
                {# Check if user is pseudo-admin #} {% if
                current_user.businessAccount == 1 %}
                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('business_admin_view.property_dashboard') }}"
                    >View Property</a
                  >
                </li>
                {% endif %}
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('auth_login_view.logout') }}"
                    >Logout</a
                  >
                </li>
              </ul>
            </li>
          </ul>
          {% else %}
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('auth_login_view.login') }}"
                >Login</a
              >
            </li>
          </ul>

          {% endif %}
          <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="#">About Nyupal</a>
            </li>
            <!-- <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>

    <!-- <div class="container"> -->
    {# Flashed Messages #} {% with messages = get_flashed_messages() %} {% if
    messages %} {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show mt-1" role="alert">
      <strong>{{ message }}</strong>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true"></span>
      </button>
    </div>
    {% endfor %} {% endif %} {% endwith %}
    
    {% block content %}
    
    {% endblock content %}
    <!-- </div> -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %} {% block content %}

<div class="container-fluid">
  <!-- Featured Content -->
  <header>
    <div class="card my-3 text-center">
      <div class="card-header">Featured Content</div>
      <div class="card-body">
        <h5 class="card-title">Relevant Ad</h5>
        <p class="card-text">Ads can be placed here</p>
        <a href="#" class="btn btn-primary">Mabati Rolling Mills</a>
      </div>
      <div class="card-footer text-muted">www.mrm.com</div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 mb-3 g-4">
      <div class="col">
        <div class="card">
          <img
            src="{{ url_for('static', filename='property/residential/d.png') }}"
            class="card-img-top"
            alt="..."
          />
          <div class="card-body">
            <h5 class="card-title">Featured: Kifaru Court</h5>
            <p class="card-text">This is the place to live!</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <img
            src="{{ url_for('static', filename='property/commercial/a.png') }}"
            class="card-img-top"
            alt="..."
          />
          <div class="card-body">
            <h5 class="card-title">Featured: Savannah Offices</h5>
            <p class="card-text">
              These exquisite and spacious offices are located in Kakamega.
            </p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- List of property -->
  <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for property in propertys.items %}
    <div class="col">
      <div class="card h-100">
        {# property.property_images #}
        <div class="my-container">
          <img
            src="{{ propertyImages[loop.index0] }}"
            class="card-img-top"
            alt="Property Image"
          />
          <!-- Star-Rating -->
          <div class="my-rating">
            <fieldset class="rating">
              <input type="radio" onclick="ratingClicked(id);" id="star5_{{ property.id }}" name="rating_{{ property.id }}" value="5" /><label
                class="full"
                for="star5_{{ property.id }}"
                title="Awesome - 5 stars"
              ></label>
              <input
                type="radio" onclick="ratingClicked(id);"
                id="star4half_{{ property.id }}"
                name="rating_{{ property.id }}"
                value="4.5"
              /><label
                class="half"
                for="star4half_{{ property.id }}"
                title="Pretty good - 4.5 stars"
              ></label>
              <input type="radio" onclick="ratingClicked(id);" id="star4_{{ property.id }}" name="rating_{{ property.id }}" value="4" /><label
                class="full"
                for="star4_{{ property.id }}"
                title="Pretty good - 4 stars"
              ></label>
              <input
                type="radio" onclick="ratingClicked(id);"
                id="star3half_{{ property.id }}"
                name="rating_{{ property.id }}"
                value="3.5"
              /><label
                class="half"
                for="star3half_{{ property.id }}"
                title="3.5 stars"
              ></label>
              <input type="radio" onclick="ratingClicked(id);" id="star3_{{ property.id }}" name="rating_{{ property.id }}" value="3" /><label
                class="full"
                for="star3_{{ property.id }}"
                title="3 stars"
              ></label>
              <input
                type="radio" onclick="ratingClicked(id);"
                id="star2half_{{ property.id }}"
                name="rating_{{ property.id }}"
                value="2.5"
              /><label
                class="half"
                for="star2half_{{ property.id }}"
                title="2.5 stars"
              ></label>
              <input type="radio" onclick="ratingClicked(id);" id="star2_{{ property.id }}" name="rating_{{ property.id }}" value="2" /><label
                class="full"
                for="star2_{{ property.id }}"
                title="2 stars"
              ></label>
              <input
                type="radio" onclick="ratingClicked(id);"
                id="star1half_{{ property.id }}"
                name="rating_{{ property.id }}"
                value="1.5"
              /><label
                class="half"
                for="star1half_{{ property.id }}"
                title="1.5 stars"
              ></label>
              <input type="radio" onclick="ratingClicked(id);" id="star1_{{ property.id }}" name="rating_{{ property.id }}" value="1" /><label
                class="full"
                for="star1_{{ property.id }}"
                title="Terrible - 1 star"
              ></label>
              <input
                type="radio" onclick="ratingClicked(id);"
                id="starhalf_{{ property.id }}"
                name="rating_{{ property.id }}"
                value="0.5"
              /><label
                class="half"
                for="starhalf_{{ property.id }}"
                title="Terrible - 0.5 stars"
              ></label>
            </fieldset>
          </div>
        </div>
        <div class="card-body">
          {% if property_verified[property.id] %}
            <div style="display: flex; justify-content: space-between; align-items: center;">
              <h4 class="card-title">{{ property.property_name }}</h4>
              <!-- <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">
                Tooltip on top
              </button> -->
              <i class="fas fa-check-circle text-primary ml-auto"></i>
            </div>
          {% else %}
            <h4 class="card-title">{{ property.property_name }}</h4>
          {% endif %}

          <p class="card-text"><b>Type:</b> {{ property.property_type }}</p>
          <p class="card-text">
            <b>Price Range:</b> {{ property.property_price }}
          </p>
          <p class="card-text">
            <b>Location:</b> {{ property.property_location }}
          </p>
        </div>
        <div class="card-footer">
          <div class="d-grid gap-2 mx-auto">
            <a
              type="button"
              href="{{ url_for('more_info_view.more_info',property_id=property.id) }}"
              class="btn btn-primary"
              >More Info</a
            >
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


<!-- Pagination Object -->
<nav aria-label="Page navigation" class="my-4">
  <ul class="pagination justify-content-center"> 
{% for page in propertys.iter_pages(left_edge=2, right_edge=2, left_current=1, right_current=2) %}
    
    {% if page %}
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    
    <li class="page-item"><a class="page-link" href="{{ url_for('main_view.index', page_num=page) }}">{{ page }}</a></li>

    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}

    {% else %}
      ...
    {% endif %}

    {% endfor %}

  </ul>
</nav>




<script>
  function ratingClicked(id){
    selected = document.getElementById(id);
    // console.log(id); // Property ID -> string -> tokenize
    // console.log(selected.value);

    // Package the data in a nicely wrapped JS Object
    ratingObject = {
      "string_id":id,
      "rating":selected.value,
    }

    // Using JavaScript's Fetch API for Async Requests
    fetch(`/rating-clicked`, {
      method: "POST",
      credentials: "include",
      body: JSON.stringify(ratingObject),
      cache:"no-cache",
      headers: new Headers({
        "content-type": "application/json",
        "X-CSRF-TOKEN":"{{ csrf_token() }}",
      })
    })
    // What to do with the server's response. <After data has been processed by the server>
    .then(function (response){
      if (response.status !== 200){
        console.log(`Request Failed with code: ${response.status}`)
        return;
      }
    })


  }
</script>

{% endblock content %}